### PR TITLE
Panic if can't find OS wordlist (Fixes #25)

### LINKED ISSUE #25: Panic if can't find OS wordlist
On Arch Linux, guess I don't have an OS wordlist: 

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ToipeError { msg: "No such file or directory (os error 2)" }', /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/toipe-0.4.0/src/main.rs:9:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
Could print a warning or just use the default word list? I can write a fix for this since I want an excuse to do rust

### PR DESCRIPTION
**Pull request by benliepert**
Improve error message context if we can't read a given word list. Add a `ToipeError` method, `with_context`, that prefixes the `msg` with a `str` you pass in. Use this method in each of the cases where `RawWordSelector` initialization can fail when initializing Toipe, so that errors from here say "Error reading the given word list: " at the front. (Fixes #25)

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -43,6 +43,16 @@ pub struct ToipeError {
     pub msg: String,
 }
 
+impl ToipeError {
+    /// Prefixes a ToipeError's msg with 'msg_context'
```
Comment (Samyak2) [inline src/lib.rs:47]: Nitpick: mentioning `ToipeError` here is redundant. This can be:
```suggestion
    /// Prefixes the message with a context
```

File: src/lib.rs [hunk 2]
```diff
@@ -43,6 +43,16 @@ pub struct ToipeError {
...
+    ///
+    /// The ToipeError operated on is consumed, and a new one is returned
```
Comment (Samyak2) [inline src/lib.rs:49]: Nitpick: This is evident from the function signature, no need to mention it here.

File: src/lib.rs [hunk 3]
```diff
@@ -43,6 +43,16 @@ pub struct ToipeError {
...
+    pub fn with_context(mut self: Self, msg_context: &str) -> Self {
```
Comment (Samyak2) [inline src/lib.rs:50]: Nitpick: the parameter can be named just `context`.

File: src/lib.rs [hunk 4]
```diff
@@ -65,13 +75,26 @@ impl<'a> Toipe {
...
+                    Ok(rws) => Box::new(rws),
+                    Err(e) => return Err(ToipeError::from(e).with_context(word_selector_error_prefix)),
+                }
             } else if let BuiltInWordlist::OS = config.wordlist {
-                Box::new(RawWordSelector::from_path(PathBuf::from(OS_WORDLIST_PATH))?)
+                let word_selector_result = RawWordSelector::from_path(PathBuf::from(OS_WORDLIST_PATH));
+                match word_selector_result {
+                    Ok(rws) => Box::new(rws),
+                    Err(e) => return Err(ToipeError::from(e).with_context(word_selector_error_prefix)),
+                }
```
Comment (Samyak2) [inline src/lib.rs:97]: There is quite a bit of repetition here, there must be a better way, but I'm not sure yet. I will get back to you on this.

**Review by Samyak2 — COMMENTED** [review]
Thank you for the PR!

It's good but I have a few comments.

Sorry for the late response, I may not respond soon for the next 3-4 days.

**Comment by Samyak2** [comment]
Also, could you add "Fixes #25" to the PR's description to link the issue here?

File: src/lib.rs (hunk 4 above)
Comment (Samyak2) [reply src/lib.rs]: I tried to make this better in a30f43fa636198c51c8f78f14f2ecc299189513c. Take a look.

**Comment by Samyak2** [comment]
There's a clippy error. Could you fix it?

**Comment by Samyak2** [comment]
I just found this crate - https://github.com/dtolnay/anyhow. It implements almost the same `with_context` function lol, but seems more convenient to use.

Let's not change anything in this PR now, but it would be nice to move to using `anyhow` in the future instead of what's being done currently.

**Comment by Samyak2** [comment]
Hey @benliepert, just checking in. Will you be able to complete this PR soon? It's completely fine if you do not find the time for it, I can wrap up the PR and merge it :)
