### PR TITLE
fix: print error message when terminal size is less the number of lines

### LINKED ISSUE #19: Show error if terminal size is too small
# What and why?

If the terminal size is too small, the lines (of words) overlap with each other and the cursor starts at the last line.

It would be nice to show an error and ask the user to maximize their window (or increase the size) to use toipe.

# How?

termion provides [terminal_size](https://docs.rs/termion/latest/termion/fn.terminal_size.html) to detect the size of the terminal. The difficulty arises in selecting a good threshold for the minimum size. It can be calculated based on the config (number of words) on the fly or can be fixed.

### PR DESCRIPTION
**Pull request by notjedi**
fixes #19 

this is my first time writing rust code, so please let me know if there is a better way of doing this.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -6,7 +6,13 @@ use toipe::Toipe;
...
     let config = ToipeConfig::parse();
 
-    let mut toipe = Toipe::new(config).unwrap();
+    let res = Toipe::new(config);
+    if let Err(e) = res {
+        eprintln!("{}", e);
+        std::process::exit(1);
+    }
+
+    let mut toipe = res.unwrap();
```
Comment (Samyak2) [inline src/main.rs:15]: This is not very nice, perhaps not "idiomatic" rust.

Instead, you can change the main function's signature to be:
```rust
fn main() -> Result<(), ToipeError>
```

This will allow us to use the `?` operator to stop at an error and print it. See the last code block in [this section](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#where-the--operator-can-be-used) of the rust book.

Though, I haven't tried this out, see if it works.

File: src/lib.rs [hunk 2]
```diff
@@ -57,6 +57,12 @@ impl From<std::io::Error> for ToipeError {
     }
 }
 
+impl std::fmt::Display for ToipeError {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        f.write_str(self.msg.as_str())
```
Comment (Samyak2) [inline src/lib.rs:62]: This doesn't provide any context about what kind of error it is. For example, if the `msg` is `file not found`, you would get just `file not found` in the terminal. Instead, I think it would be better to print `ToipeError: File not found`.

File: src/tui.rs [hunk 3]
```diff
@@ -403,6 +403,15 @@ impl ToipeTui {
         //   - won't hang there waiting for user to type space
         lines.push(Text::from(line.join(" ")).with_faint());
 
+        if lines.len() >= terminal_height.into() {
+            return Err(ToipeError {
+                msg: format!(
+                    "toipe requires atleast {} lines in your terminal",
+                    lines.len()
+                ),
+            });
```
Comment (Samyak2) [inline src/tui.rs:412]: This is good, but can be improved a bit. You could `impl From<&str> for ToipeError` (or perhaps `impl From<String> for ToipeError` to avoid references) and construct a `ToipeError` inside it taking a string.

Then this part will reduce to:
```rust
return Err(ToipeError::from(format!("toipe requires atleast {} lines in your terminal", lines.len())))
```

**Review by Samyak2 — CHANGES_REQUESTED** [review]
Thanks!

I had some comments.

Also, I was concerned about another thing. The size could be restricted by width too - some tiling WMs can make windows be very long and thin. We should also check to see if the longest line fits on the terminal.

**Comment by Samyak2** [comment]
Also, could you link the issue by adding "Fixes #19" in your PR's description?

File: src/lib.rs (hunk 2 above)
Comment (notjedi) [reply src/lib.rs]: done. the new error would be `Error: ToipeError: error_msg`.

File: src/tui.rs (hunk 3 above)
Comment (notjedi) [reply src/tui.rs]: implemented `From<String>` for `ToipeError`. and refactored code.

File: src/main.rs (hunk 1 above)
Comment (notjedi) [reply src/main.rs]: it does work, so i changed it to they way you wanted.

File: src/main.rs [hunk 4]
```diff
@@ -2,11 +2,12 @@ use clap::StructOpt;
...
+use toipe::ToipeError;
 
-fn main() {
+fn main() -> Result<(), ToipeError> {
     let config = ToipeConfig::parse();
 
-    let mut toipe = Toipe::new(config).unwrap();
+    let mut toipe = Toipe::new(config)?;
 
     let stdin = stdin();
```
Comment (Samyak2) [inline src/main.rs:13]: The `unwrap()` below on line 17 can also be replaced with a `?` with this change

File: src/tui.rs [hunk 5]
```diff
@@ -403,6 +409,18 @@ impl ToipeTui {
         //   - won't hang there waiting for user to type space
         lines.push(Text::from(line.join(" ")).with_faint());
 
+        if lines.len() + self.bottom_lines_len + 1 >= terminal_height.into() {
+            return Err(ToipeError::from(format!(
+                "toipe requires atleast {} lines in your terminal",
```
Comment (Samyak2) [inline src/tui.rs:414]: nitpick: the message can better written and would be nice to display the current height too:
```suggestion
                "Terminal height is too short! Toipe requires at least {} lines, got {} lines",
```

File: src/tui.rs [hunk 6]
```diff
@@ -403,6 +409,18 @@ impl ToipeTui {
...
+                lines.len() + self.bottom_lines_len + 1
+            )));
+        } else if max_word_len >= max_width.into() {
+            return Err(ToipeError::from(format!(
+                "toipe requires atleast {} columns in your terminal",
```
Comment (Samyak2) [inline src/tui.rs:419]: Same here:
```suggestion
                "Terminal width is too low! Toipe requires at least {} columns, got {} columns",
```

File: src/tui.rs [hunk 7]
```diff
@@ -403,6 +409,18 @@ impl ToipeTui {
         //   - won't hang there waiting for user to type space
         lines.push(Text::from(line.join(" ")).with_faint());
 
+        if lines.len() + self.bottom_lines_len + 1 >= terminal_height.into() {
+            return Err(ToipeError::from(format!(
+                "toipe requires atleast {} lines in your terminal",
+                lines.len() + self.bottom_lines_len + 1
+            )));
+        } else if max_word_len >= max_width.into() {
+            return Err(ToipeError::from(format!(
```
Comment (Samyak2) [inline src/tui.rs:418]: There is an issue with this. When the error occurs in between restarts, the errors gets printed first and then the screen gets cleared (by the `Drop` trait implementation of `ToipeTui`). So it appears as if toipe crashed without any message. Some terminals don't show the error even when scrolling back up (for me Alacritty showed the error as I scrolled up but Konsole did not).

I'm not sure how to work around this yet. It's okay if this can't be solved in this PR but would be nice to add a TODO somewhere, probably in the `impl Drop for ToipeTui`.

File: src/tui.rs [hunk 8]
```diff
@@ -403,6 +409,18 @@ impl ToipeTui {
         //   - won't hang there waiting for user to type space
         lines.push(Text::from(line.join(" ")).with_faint());
 
+        if lines.len() + self.bottom_lines_len + 1 >= terminal_height.into() {
```
Comment (Samyak2) [inline src/tui.rs:412]: The `into()` here is to convert `u16` into `usize`, right? If so, it would be better to do `as usize` since it's used in the rest of the code.

**Review by Samyak2 — COMMENTED** [review]
This is looking good!

I had a few minor suggestions and a comment though.

File: src/tui.rs (hunk 8 above)
Comment (notjedi) [reply src/tui.rs:412]: yeah, it is. i changed it to `as usize`.

File: src/main.rs (hunk 4 above)
Comment (notjedi) [reply src/main.rs:13]: okay cool. done

File: src/tui.rs (hunk 6 above)
Comment (notjedi) [reply src/tui.rs:419]: 👍

File: src/tui.rs (hunk 5 above)
Comment (notjedi) [reply src/tui.rs:414]: 👍🏼

File: src/tui.rs (hunk 7 above)
Comment (notjedi) [reply src/tui.rs:418]: good catch. even i'm not sure how to solve this yet. i'll open a new pr if i find a way to do this. adding a `TODO` comment, with a link to this discussion, as of now.

**Comment by notjedi** [comment]
i pushed a new commit with all the changes, do take a final look at it. also i appreciate you being patient and guiding me on writing rust for the first time. thank you.

**Review by Samyak2 — APPROVED** [review]
LGTM. Thank you!

File: src/tui.rs [hunk 9]
```diff
@@ -393,7 +398,8 @@ impl ToipeTui {
 
                 // clear line
                 line = Vec::new();
-                current_len = 0;
+                line.push(word.clone());
+                current_len = word.len() as u16 + 1;
```
Comment (Samyak2) [inline src/tui.rs:402]: One question about this - does this mean that a word was being skipped after a line was completed?

File: src/tui.rs [hunk 10]
```diff
@@ -403,6 +409,19 @@ impl ToipeTui {
         //   - won't hang there waiting for user to type space
         lines.push(Text::from(line.join(" ")).with_faint());
 
+        if lines.len() + self.bottom_lines_len + 1 >= terminal_height as usize {
+            return Err(ToipeError::from(format!(
+                "Terminal height is too short! Toipe requires at least {} lines, got {} lines",
+                lines.len() + self.bottom_lines_len + 1,
```
Comment (Samyak2) [inline src/tui.rs:415]: Noticed one more thing. This value should be one extra. When `lines.len() + self.bottom_lines_len + 1` == `terminal_height`. The message will look like `Toipe requires at least 10 lines, got 10 lines`

File: src/tui.rs [hunk 11]
```diff
@@ -403,6 +409,19 @@ impl ToipeTui {
...
+                terminal_height,
+            )));
+        } else if max_word_len >= max_width as usize {
+            return Err(ToipeError::from(format!(
+                "Terminal width is too low! Toipe requires at least {} columns, got {} columns",
```
Comment (Samyak2) [inline src/tui.rs:420]: Same here. When `max_word_len == max_width`, the error isn't right

**Review by Samyak2 — CHANGES_REQUESTED** [review]

File: src/tui.rs [hunk 12]
```diff
@@ -371,15 +374,17 @@ impl ToipeTui {
...
         let mut lines = Vec::new();
-        let (terminal_width, _) = terminal_size()?;
+        let (terminal_width, terminal_height) = terminal_size()?;
         // 40% of terminal width
         let max_width = terminal_width * 2 / 5;
         const MAX_WORDS_PER_LINE: usize = 10;
         // eprintln!("max width is {}", max_width);
 
         for word in words {
+            max_word_len = std::cmp::max(max_word_len, word.len() + 1);
```
Comment (Samyak2) [inline src/tui.rs:387]: There is another issue with the width calculation. Here you only consider the size of individual words. If the largest word fits in the width, it's allowed. But even if the words fit, the keybinds at the bottom and the results screen won't. Example:
Spectacle_last

I think it would be best to hardcode the width for now. The longest line in my results was `Mistakes: 150 out of 158 characters` which is 35 chars. `50` seems like a reasonable number to use as the minimum width.

What do you think?

**Review by Samyak2 — CHANGES_REQUESTED** [review]
One more thing. Sorry for requesting so many changes xD, but I want to get this right.

File: src/tui.rs (hunk 12 above)
Comment (notjedi) [reply src/tui.rs:387]: i actually accounted for the bottom text as the number of lines. so this actually depends on your choice. i personally think setting a fixed base width would be better(i'm prolly biased here) and is little more appealing. but also since the text is not cut off, ig it is okay to have it just like this(maybe some will prefer typing in a narrow terminal). this is just a design choice that you should decide at the end. anyways i would be happy to refactor the code if needed.

File: src/tui.rs (hunk 9 above)
Comment (notjedi) [reply src/tui.rs:402]: yeah, when the terminal was too small, the number of words were like less than 10. so i looked through the code and found that each time when a line is completed, the current word was skipped(which caused the <10 words issue). so yeah i also fixed this minor bug

File: src/tui.rs (hunk 10 above)
Comment (notjedi) [reply src/tui.rs]: done

File: src/tui.rs (hunk 11 above)
Comment (notjedi) [reply src/tui.rs:420]: done

File: src/tui.rs (hunk 12 above)
Comment (notjedi) [reply src/tui.rs:387]: btw, if we are hardcoding the value, 50 does seem reasonable.

File: src/tui.rs (hunk 9 above)
Comment (Samyak2) [reply src/tui.rs:402]: nice! thanks

File: src/tui.rs (hunk 12 above)
Comment (Samyak2) [reply src/tui.rs:387]: > i actually accounted for the bottom text as the number of lines. so this actually depends on your choice.

yes, the height (number of lines) is fine. it's good to have that be calculated from the actual number of chars that are used rather than hardcoding it. my concern was about the width (columns) only.

> i personally think setting a fixed base width would be better(i'm prolly biased here) and is little more appealing.

that's a good idea. something like checking if it's more than the base width (50 chars) and more than the largest word would be nice. it would be pretty rare to have words >50 chars but i wouldn't discount it since this is a typing test app.

> but also since the text is not cut off, ig it is okay to have it just like this(maybe some will prefer typing in a narrow terminal). 

the text *is* cut off. see the screenshot i attached above - `Mistakes 127 out of 14` isn't right (there were much more than 14 chars). it does wrap into the next line but that's overwritten by `Speed: ...`.

File: src/tui.rs [hunk 13]
```diff
@@ -393,7 +398,8 @@ impl ToipeTui {
 
                 // clear line
                 line = Vec::new();
-                current_len = 0;
+                line.push(word.clone());
```
Comment (Samyak2) [inline src/tui.rs:401]: you can have it in the vec while creating it.
```rust
line = vec![word.clone()];
```

Comment (notjedi) [reply src/tui.rs]: done

File: src/tui.rs (hunk 12 above)
Comment (notjedi) [reply src/tui.rs:387]: currently hard coded a value of 50.

**Review by Samyak2 — APPROVED** [review]
LGTM.

Thank you for contributing and for your patience! :tada:
